import { Pipe, PipeTransform } from '@angular/core';


@Pipe({
  name: 'country'
})
export class Country implements PipeTransform {

  transform (country:string){
    if (country === 'BA') return 'Bosnia & Herzegovine';
    if (country === 'RU') return 'Russia';
    if (country === 'AR') return 'Argentina';
    if (country === 'AU') return 'Australia';
    if (country === 'GB') return 'United Kingdom';
    if (country === 'US') return 'United States';
    if (country === 'RS') return 'Serbia';
    if (country === 'CN') return 'China';
    if (country === 'LY') return 'Lybia';
    if (country === 'PA') return 'Panama';
    if (country === 'PT') return 'Portugal';
    if (country === 'BR') return 'Brasil';
    if (country === 'JP') return 'Japan';
    if (country === 'IN') return 'India';
    if (country === 'DK') return 'Denmark';
    if (country === 'EG') return 'Egypt';
    if (country === 'FR') return 'France';
    if (country === 'CA') return 'Canada';
    if (country === 'DE') return 'Germany';
    if (country === 'IS') return 'Iceland';
    if (country === 'IT') return 'Italy';
    if (country === 'ME') return 'Montenegro';
    if (country === 'HR') return 'Croatia';
    if (country === 'KH') return 'Cambodia';
    if (country === 'ID') return 'Indonesia';
    if (country === 'AO') return 'Angola';
    if (country === 'NG') return 'Nigeria';
    if (country === 'CL') return 'Chile';
    if (country === 'ZM') return 'Zambia';
    if (country === 'NZ') return 'New Zealand';
    if (country === 'UZ') return 'Uzbekistan';
    if (country === 'GL') return 'Greenland';
    if (country === 'CG') return 'Congo';
    if (country === 'BE') return 'Belgium';
    if (country === 'SE') return 'Sweden';
    if (country === 'ES') return 'Spain';
    if (country === 'TR') return 'Turkey';
    if (country === 'AT') return 'Austria';
    if (country === 'BY') return 'Belarus';
    if (country === 'AF') return 'Afghanistan';
    if (country === 'AS') return 'American Samoa';
    if (country === 'AD') return 'Andorra';
    if (country === 'AI') return 'Anguilla';
    if (country === 'AQ') return 'Antarctica';
    if (country === 'AW') return 'Aruba';
    if (country === 'AL') return 'Albania';
    if (country === 'DZ') return 'Algeria';
    if (country === 'AZ') return 'Azerbaijan';
    if (country === 'BD') return 'Bangladesh';
    if (country === 'BZ') return 'Belize';
    if (country === 'BJ') return 'Benin';
    if (country === 'BT') return 'Bhutan';
    if (country === 'BO') return 'Bolivia';
    if (country === 'BW') return 'Botswana';
    if (country === 'BG') return 'Bulgaria';
    if (country === 'BI') return 'Burundi';
    if (country === 'BN') return 'Brunei';
    if (country === 'BS') return 'Bahamas';
    if (country === 'BH') return 'Bahrain';
    if (country === 'BB') return 'Barbados';
    if (country === 'BM') return 'Bermuda';
    if (country === 'CV') return 'Cape Verde';
    if (country === 'KY') return 'Cayman Islands';
    if (country === 'CX') return 'Chrismas Islands';
    if (country === 'CC') return 'Cocos Islands';
    if (country === 'CK') return 'Cook Islands';
    if (country === 'CW') return 'Curacao';
    if (country === 'BF') return 'Burkina Faso';
    if (country === 'KH') return 'Cambodia';
    if (country === 'CM') return 'Cameroon';
    if (country === 'CF') return 'Central African Republic';
    if (country === 'CO') return 'Colombia';
    if (country === 'KM') return 'Comoros';
    if (country === 'CD') return 'The Democratic Republic of the Congo';
    if (country === 'CR') return 'Costa Rica';
    if (country === 'CU') return 'Cuba';
    if (country === 'CY') return 'Cyprus';
    if (country === 'CZ') return 'Czechia';
    if (country === 'CI') return 'Cote d Ivoire';
    if (country === 'DJ') return 'Djibouti';
    if (country === 'DM') return 'Dominica';
    if (country === 'DO') return 'Dominican Republic';
    if (country === 'EC') return 'Ecuador';
    if (country === 'IM') return 'Isle of Man';
    if (country === 'SV') return 'El Salvador';
    if (country === 'GQ') return 'Ecuatorial Guinea';
    if (country === 'ER') return 'Eritrea';
    if (country === 'EE') return 'Estonia';
    if (country === 'ET') return 'Ethiopia';
    if (country === 'FK') return 'Falkland Islands';
    if (country === 'FO') return 'Faroe Islands';
    if (country === 'FJ') return 'Fiji';
    if (country === 'FI') return 'Finland';
    if (country === 'GF') return 'French Guiana';
    if (country === 'GA') return 'Gabon';
    if (country === 'GM') return 'Gambia';
    if (country === 'GE') return 'Georgia';
    if (country === 'GH') return 'Ghana';
    if (country === 'GI') return 'Gibraltar';
    if (country === 'GR') return 'Greece';
    if (country === 'GD') return 'Grenada';
    if (country === 'GP') return 'Guadeloupe';
    if (country === 'GU') return 'Guam';
    if (country === 'GT') return 'Guatemala';
    if (country === 'GN') return 'Guinea';
    if (country === 'GW') return 'Guinea-Bissau';
    if (country === 'GY') return 'Guyana';
    if (country === 'HT') return 'Haiti';
    if (country === 'HN') return 'Honduras';
    if (country === 'HK') return 'Hong Kong';
    if (country === 'HU') return 'Hungary';
    if (country === 'IR') return 'Iran';
    if (country === 'IQ') return 'Iraq';
    if (country === 'IE') return 'Ireland';
    if (country === 'IL') return 'Israel';
    if (country === 'JM') return 'Jamaica';
    if (country === 'JE') return 'Jersey';
    if (country === 'JO') return 'Jordan';
    if (country === 'KZ') return 'Kazakhstan';
    if (country === 'KE') return 'Kenya';
    if (country === 'KI') return 'Kiribati';
    if (country === 'KP') return 'the Democratic Peoples Republic of Korea';
    if (country === 'KR') return 'the Republic of Korea';
    if (country === 'KW') return 'Kuwait';
    if (country === 'KG') return 'Kyrgyzstan';
    if (country === 'LA') return 'Laos';
    if (country === 'LV') return 'Latvia';
    if (country === 'LB') return 'Lebanon';
    if (country === 'LS') return 'Lesotho';
    if (country === 'LR') return 'Liberia';
    if (country === 'MO') return 'Macao';
    if (country === 'LI') return 'Lithuania';
    if (country === 'LT') return 'Latvia';
    if (country === 'LU') return 'Luxembourg';

    if (country === 'MG') return 'Madagascar';
    if (country === 'MW') return 'Malavi';
    if (country === 'MY') return 'Malaysia';
    if (country === 'MV') return 'Maldives';
    if (country === 'ML') return 'Mali';
    if (country === 'MT') return 'Malta';
    if (country === 'MH') return 'Marshall Islands';
    if (country === 'MQ') return 'Martinique';
    if (country === 'MR') return 'Mauritania';
    if (country === 'MU') return 'Mauritius';
    if (country === 'YT') return 'Mayotte';
    if (country === 'MX') return 'Mexico';
    if (country === 'FM') return 'Micronesia';
    if (country === 'MD') return 'Moldova';
    if (country === 'MC') return 'Monaco';
    if (country === 'MN') return 'Mongolia';
    if (country === 'MS') return 'Montserrat';
    if (country === 'MA') return 'Morocco';
    if (country === 'MZ') return 'Mozambique';
    if (country === 'MM') return 'Myanmar';
    if (country === 'NA') return 'Namiibia';
    if (country === 'NR') return 'Nauru';
    if (country === 'NP') return 'Nepal';
    if (country === 'NL') return 'Netherlands';
    if (country === 'NC') return 'New Caledonia';
    if (country === 'NI') return 'Nicaragua';
    if (country === 'NE') return 'Niger';
    if (country === 'NU') return 'Niue';
    if (country === 'NF') return 'Norfolk Island';
    if (country === 'MP') return 'Northen Mariana Islands';
    if (country === 'NO') return 'Norway';
    if (country === 'OM') return 'Oman';
    if (country === 'PK') return 'Pakistan';
    if (country === 'PW') return 'Palau';
    if (country === 'PS') return 'Palestine';
    if (country === 'PE') return 'Peru';
    if (country === 'PG') return 'Papua New Guinea';
    if (country === 'PY') return 'Paraguay';
    if (country === 'PH') return 'Phiilippines';
    if (country === 'PN') return 'Pitcairn';
    if (country === 'PL') return 'Poland';
    if (country === 'PR') return 'Puerto Rico';
    if (country === 'QA') return 'Quatar';
    if (country === 'MK') return 'North Macedonia';
    if (country === 'RO') return 'Romania';
    if (country === 'RW') return 'Rwanda';
    if (country === 'RE') return 'Réunion';
    if (country === 'BL') return 'Saint Barthélemy';
    if (country === 'SH') return 'Saint Helena, Ascension and Tristan da Cunha';
    if (country === 'KN') return 'Saint Kitts and Nevis';
    if (country === 'LC') return 'Saint Lucia	';
    if (country === 'MF') return 'Saint Martin';
    if (country === 'PM') return 'Saint Pierre and Miquelon';
    if (country === 'VC') return 'Saint Vincent and the Grenadines';
    if (country === 'WS') return 'Samoa';
    if (country === 'SM') return 'San Marino';
    if (country === 'ST') return 'Sao Tome and Principe';
    if (country === 'SA') return 'Saudi Arabia';
    if (country === 'SN') return 'Senegal';
    if (country === 'SC') return 'Seychelles';
    if (country === 'SL') return 'Sierra Leone';
    if (country === 'SG') return 'Singapore';
    if (country === 'SO') return 'Somalia';
    if (country === 'SX') return 'Sint Maarten';
    if (country === 'SK') return 'Slovakia';
    if (country === 'SI') return 'Slovenia';
    if (country === 'SB') return 'Solomon Islands';
    if (country === 'ZA') return 'South Africa';
    if (country === 'GS') return 'South Georgia and the South Sandwich Islands';
    if (country === 'SS') return 'South Sudan';
    if (country === 'LK') return 'Sri Lanka';
    if (country === 'SD') return 'Sudan';
    if (country === 'SR') return 'Suriname';
    if (country === 'SJ') return 'Svalbard and Jan Mayen';
    if (country === 'CH') return 'Switzerland';
    if (country === 'SY') return 'Syrian Arab Republic';
    if (country === 'TW') return 'Taiwan';
    if (country === 'TJ') return 'Tajikistan';
    if (country === 'TZ') return 'Tanzania';
    if (country === 'TH') return 'Thailand';
    if (country === 'TL') return 'Timor-Leste';
    if (country === 'TG') return 'Togo';
    if (country === 'TK') return 'Tokelau';
    if (country === 'TO') return 'Tonga';
    if (country === 'TT') return 'Trinidad and Tobago';
    if (country === 'TN') return 'Tunisia';
    if (country === 'TM') return 'Turkmenistan';
    if (country === 'TC') return 'Turks and Caicos Islands';
    if (country === 'TV') return 'Tuvalu';
    if (country === 'UG') return 'Uganda';
    if (country === 'UA') return 'Ukraine';
    if (country === 'AE') return 'United Arab Emirates';
    if (country === 'UM') return 'United States Minor Outlying Islands';
    if (country === 'UY') return 'Uruguay';
    if (country === 'VU') return 'Vanuatu';
    if (country === 'VE') return 'Venezuela';
    if (country === 'VN') return 'Vietnam';
    if (country === 'VG') return 'Virgin Islands (British)';
    if (country === 'VI') return 'Virgin Islands (U.S.)';
    if (country === 'WF') return 'Wallis and Futuna';
    if (country === 'EH') return 'Western Sahara';
    if (country === 'YE') return 'Yemen';
    if (country === 'ZM') return 'Zambia';
    if (country === 'ZW') return 'Zimbabwe';
    if (country === 'AX') return 'Åland Islands';
    if (country === 'PF') return 'French Polynesia';
    if (country === 'TD') return 'Chad';
    if (country === 'CK') return 'Cook Islands';

    return country;
  }





}
